name: Remote Verify
on: [push, pull_request] 

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Formatter
        run: bun run format 
      - name: Run Tests
        run: bun run test 